apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-manager-config
  namespace: nip
data:
  SPRING_PROFILES_ACTIVE: prod

  CONFIG_SERVER_HOST: config-server
  CONFIG_SERVER_PORT: "8088"

  EUREKA_SERVER_URL: http://service-registery:8761/eureka
  USER_MANAGER_URL: http://user-manager:8082


