apiVersion: v1
kind: Secret
metadata:
  name: auth-manager-secret
  namespace: nip
type: Opaque
stringData:
  SPRING_SECURITY_USER_PASSWORD: "password"
  JWT_SECRET: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
  SPRING_SECURITY_USER_NAME: "user"