spring:
  config:
    import: optional:configserver:http://localhost:8088
  mail:
    host: smtp.gmail.com
    port: 587
    username: hechemmohamed9@gmail.com
    password: opql uupj vnys wvaq
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
app:
  sms:
    from: "whatsapp:+14155238886"
    account-sid: "AC068aaa19c8104b2d6c0ec49f06192795"
    auth-token: "c52e1f3cc83fd4b69f0e13844f0ad2fc"

firebase:
  project-id: ""
  client-email: ""
  private-key: ""
