server:
  port: 8095
spring:
  application:
    name: notification-manager
  mail:
    host: smtp.gmail.com
    port: 587
    username: hechemmohamed9@gmail.com
    password: opql uupj vnys wvaq
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  amqp:
    deserialization:
      trust-all: true
  rabbitmq:
    host: localhost  # plus tard docker : rabbitmq
    port: 5672
    username: guest
    password: guest

  # Nom de la queue / exchange / routing key
  notifications:
    queue: user.notifications
    exchange: userExchange
    routing-key: user.registered
  profiles:
    active: test
app:
  sms:
    queue: sms-queue
    exchange: smsExchange
    routing-key: sms.send
    provider: whatsapp
    from: "whatsapp:+14155238886"
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}

