server:
  port: 8095
spring:
  profiles:
    active: local
  application:
    name: notification-manager
  amqp:
    deserialization:
      trust-all: true
  notifications:
    queue: user.notifications
    exchange: userExchange
    routing-key: user.registered
app:
  sms:
    queue: sms-queue
    exchange: smsExchange
    routing-key: sms.send
    provider: whatsapp
