server:
  port: 8090
security:
  public:
    endpoints: /auth/**,
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8088"
  cloud:
    gateway:
      routes:
        - id: auth-manager
          uri: lb://auth-manager
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-manager
          uri: lb://user-manager
          predicates:
            - Path=/user/v1/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true