server:
  port: 8097
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
  application:
    name: ai-content-generator-manager
  rabbitmq:
    host: ${RABBITMQ_HOST}.nip-infra.svc.cluster.local
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
LLM:
  HOST: ${OLLAMA_HOST}.nip-infra.svc.cluster.local
  PORT: ${OLLAMA_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}