apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-manager-config
  namespace: nip
data:
  SPRING_PROFILES_ACTIVE: prod

  CONFIG_SERVER_HOST: config-server
  CONFIG_SERVER_PORT: "8088"

  EUREKA_SERVER_URL: http://service-registery:8761/eureka


  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"


  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  NOTIFICATIONS_QUEUE: "user.notifications"
  NOTIFICATIONS_EXCHANGE: "userExchange"
  NOTIFICATIONS_ROUTING_KEY: "user.registered"

  SMS_QUEUE: "sms-queue"
  SMS_EXCHANGE: "smsExchange"
  SMS_ROUTING_KEY: "sms.send"
