apiVersion: v1
kind: Service
metadata:
  name: notification-manager
  namespace: nip
spec:
  type: ClusterIP
  selector:
    app: notification-manager
  ports:
    - port: 8095
      targetPort: 8095
