apiVersion: v1
kind: Secret
metadata:
  name: user-manager-secret
  namespace: nip
type: Opaque
stringData:
  SMS_FROM: whatsapp:+14155238886
  SMS_ACCOUNT_SID: AC068aaa19c8104b2d6c0ec49f06192795
  SMS_AUTH_TOKEN: 400a6ac2bdd3b023273a7587110bc010
  project-id: ""
  client-email: ""
  private-key: ""
  MAIL_USERNAME: hechemmohamed9@gmail.com
  MAIL_PASSWORD: opql uupj vnys wvaq
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest