apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-content-generator-manager-config
  namespace: nip
data:
  SPRING_PROFILES_ACTIVE: prod

  CONFIG_SERVER_HOST: config-server
  CONFIG_SERVER_PORT: "8088"

  EUREKA_SERVER_URL: http://service-registery:8761/eureka


  LLM_HOST: ollama
  LLM_PORT: "11434"

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
