apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: nip-infra
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: ${RABBITMQ_AMQP_PORT}
      targetPort: ${RABBITMQ_AMQP_PORT}
    - name: management
      port: ${RABBITMQ_MANAGEMENT_PORT}
      targetPort: ${RABBITMQ_MANAGEMENT_PORT}
