server:
  port: 8087

spring:
  application:
    name: auth-manager

  config:
      import: "optional:configserver:http://config-server:8088"

  security:
    user:
      name: "user"
      password: "password"

logging:
  level:
    org.springframework.web: INFO

token: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"

usermanager:
  url: "http://user-manager:8082"
