server:
  port: 8087
spring:
  application:
    name: auth-manager
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  security:
    user:
      name: user
      password: password
jwt:
  secret: ${JWT_SECRET}
user-manager:
  url:  ${USER_MANAGER_URL}





