server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-manager
    config:
      import: "optional:configserver:http://localhost:8088"

  security:
    user:
      name: "user"
      password: "password"

logging:
  level:
    org.springframework.web: INFO

token: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"

usermanager:
  url: "http://localhost:8082"  # port of User Manager MS
