server:
  port: 8082

spring:
  config:
    import: optional:configserver:http://localhost:8088

  datasource:
    url: jdbc:mysql://localhost:3306/usermanagerdb
    username: root
    password: root
