apiVersion: v1
kind: ConfigMap
metadata:
  name: user-manager-config
  namespace: nip
data:
  SPRING_PROFILES_ACTIVE: prod

  CONFIG_SERVER_HOST: config-server
  CONFIG_SERVER_PORT: "8088"

  EUREKA_SERVER_URL: http://service-registery:8761/eureka

  DB_HOST: mysql
  DB_PORT: "3306"
