apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  namespace: nip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
        - name: user-manager
          image: hachem27/user-manager:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: user-manager-config
            - secretRef:
                name: user-manager-secret

